# PostgreSQL Backup Configuration



source:
# Database name to backup
  database_name: victor
# Directory where backups will be stored
  backup_dir: ~/backup
# PostgreSQL user
  pg_user: victor
# PostgreSQL port
  port: 5432
# PostgreSQL host
  host: localhost
# Backup format: c (custom), t (tar), p (plain), d (directory)
  backup_format: d

target:
  # Target host for backup (can be the same as source)
  host: 192.168.1.245 
  # SSH user for target host
  user: admin
  # SSH port for target host
  port: 9543
  # Directory on target host where backup will be stored
  path: /home/admin/backups/remote
  # Path to SSH private key for authenticationk
  ssh_keys: ~/.ssh/id_rsa
